### PR TITLE
Ignore .git files

### PR DESCRIPTION
**Pull request by matt-lumer**
This causes issues on Windows machines due to file handles not being released

*Issue #, if available:*

*Description of changes:*
Added .git to the list of excluded files, similar to the python one which has additional files.
.git causes "WindowsError: [Error 5] Access is denied: c:\\temp\\.git\\objects\\*"

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by TheSriram** [comment]
Thanks for this change! is there a unit test you could write for this as well?

**Comment by kamilfb** [comment]
I've had the same issue on Windows 10 and implementing the fix locally does resolve the problem.

**Comment by khamaileon** [comment]
@matt-lumer .git files are ignored since the last release. You should cancel your pull request.

**Comment by matt-lumer** [comment]
@khamaileon Can you show me where this change was made?  I checked this source file and found 
 no changes are made in develop or master.  I confirmed also CopySource itself is not changed.  I also downloaded version 21 and I see the same error

JavaMavenWorkflow:MavenCopyArtifacts failed
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\mlumer\\AppData\\Local\\Temp\\tmpq_zfvkcg\\**.git**\\objects\\pack\\pack-c29e65c05c1a495bc4d83ba6a70fc1fad621ae75.idx'

sam --version
SAM CLI, version 0.21.0

**Comment by khamaileon** [comment]
@matt-lumer Sorry mate, I was looking at the [python builder](https://github.com/awslabs/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/python_pip/workflow.py). There should be a way to globally include or exclude files inside serverless.yml. It would solve a lot of packaging issues..

**Comment by matt-lumer** [comment]
Np, I got all excited :)  Yes ultimately I agree it would be nice to have configuration through the files and not buried within the app.  Java really suffers from having a subdirectory so I'll get on the unit test and hopefully we'll have this promoted

**Comment by matt-lumer** [comment]
@TheSriram I added the unit test, sorry for such a long delay.  Can you review?

**Comment by matt-lumer** [comment]
@sanathkr @jfuss If anyone can do a quick sign off, this should be fast and would be appreciated!

**Comment by awood45** [comment]
Thanks for the contribution!

**Comment by matt-lumer** [comment]
@awood45 Thanks so much!!

**Pull request merged**
